name: Check Bundle Size

on:
  pull_request:
    branches:
      - 'main'

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  bundle:
    name: Check Bundle Size
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      
      - run: npm install esbuild
      
      - name: Check Bundle Size
        uses: actions/github-script@v6
        with:
          script: |
            const { default: script } = await import('${{ github.workspace }}/.github/bundle-size.mjs')
            await script({ github, context })
