name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - '.vscode/**'
      - '**/*.md'


defaults:
  run:
    shell: bash

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
  FORCE_COLOR: true
  ASTRO_TELEMETRY_DISABLED: true

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: env
