name: 'Mirror Templates'

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: mirror examples
        run: "${GITHUB_WORKSPACE}/.github/scripts/mirror.sh" examples
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
