name: 'Mirror Templates'

on:
  push:
    branches:
      - main
    tags:
      - '*'

env:
  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: mirror examples
        runs: ../scripts/mirror.sh examples
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: examples natemoo-re template
